# Generated by Django 4.2.3 on 2023-07-20 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='test@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='contact',
            name='review',
            field=models.CharField(default='verry good website', max_length=200),
        ),
        migrations.AddField(
            model_name='contact',
            name='sem',
            field=models.CharField(default='3rd', max_length=4),
        ),
    ]
